# Generated by Django 4.0.3 on 2022-03-07 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
