# Generated by Django 4.0.3 on 2022-03-08 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=50)),
                ('venue_address', models.TextField()),
                ('description', models.TextField()),
                ('pic_name', models.ImageField(default='', max_length=255, upload_to='kidzapp/event_pic')),
            ],
        ),
    ]
