# Generated by Django 4.0.3 on 2022-03-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0005_parentlogin_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('address', models.TextField()),
                ('pic_name', models.FileField(default='', upload_to='kidzapp/picture')),
            ],
        ),
    ]
