# Generated by Django 4.0.3 on 2022-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0007_parentreg_delete_parentlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parentreg',
            name='id',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parentreg',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
