# Generated by Django 4.0.3 on 2022-03-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0008_remove_organizer_id_remove_parentreg_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parentreg',
            new_name='Parent',
        ),
    ]
