# Generated by Django 4.0.3 on 2022-04-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0011_remove_user_message_user1_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Model',
            fields=[
                ('activity_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=45)),
                ('age_group', models.CharField(max_length=45)),
                ('fees', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kidzapp.organizer')),
            ],
        ),
    ]
