# Generated by Django 4.0.3 on 2022-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0012_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=45)),
                ('age_group', models.CharField(max_length=45)),
                ('fees', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kidzapp.organizer')),
            ],
        ),
        migrations.DeleteModel(
            name='Activity_Model',
        ),
    ]
