# Generated by Django 4.0.3 on 2022-04-05 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0013_activity_models_delete_activity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField()),
                ('kid_name', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('school_name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('father_name', models.CharField(max_length=45)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('transaction_id', models.CharField(max_length=45)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('parent_user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kidzapp.parent')),
            ],
        ),
    ]
