# Generated by Django 4.0.3 on 2022-04-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kidzapp', '0014_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kidzapp.parent'),
        ),
    ]
